kind: PersistentVolume
apiVersion: v1
metadata:
  name: vault-pv
  labels:
    type: local
spec:
  storageClassName: vault
  capacity:
    storage: 10Gi
  local:
    path: /data/vault
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-2
